(defun convertascii (parameter)
  (interactive "sconvert ascii to strings:")
  (cond
   ((string= parameter "33") (setq str "!"))
   ((string= parameter "34") (setq str "\""))
   ((string= parameter "35") (setq str "#"))
   ((string= parameter "36") (setq str "$"))
   ((string= parameter "37") (setq str "%"))
   ((string= parameter "38") (setq str "&"))
   ((string= parameter "39") (setq str "'"))
   ((string= parameter "40") (setq str "("))
   ((string= parameter "41") (setq str ")"))
   ((string= parameter "42") (setq str "*"))
   ((string= parameter "43") (setq str "+"))
   ((string= parameter "44") (setq str ","))
   ((string= parameter "45") (setq str "-"))
   ((string= parameter "46") (setq str "."))
   ((string= parameter "47") (setq str "/"))
   ((string= parameter "48") (setq str "0"))
   ((string= parameter "49") (setq str "1"))
   ((string= parameter "50") (setq str "2"))
   ((string= parameter "51") (setq str "3"))
   ((string= parameter "52") (setq str "4"))
   ((string= parameter "53") (setq str "5"))
   ((string= parameter "54") (setq str "6"))
   ((string= parameter "55") (setq str "7"))
   ((string= parameter "56") (setq str "8"))
   ((string= parameter "57") (setq str "9"))
   ((string= parameter "58") (setq str ":"))
   ((string= parameter "59") (setq str ";"))
   ((string= parameter "60") (setq str "<"))
   ((string= parameter "61") (setq str "="))
   ((string= parameter "62") (setq str ">"))
   ((string= parameter "63") (setq str "?"))
   ((string= parameter "64") (setq str "@"))
   (t (setq str "UNKNOWN")))
  (message "%s" str)
  )
